VERSION: ${pom.version}
common:
    pageSize: 15
warp:
    minNameLength: 3
    maxNameLength: 25
warpCounter:
    private:
        x: 0
        default: 0
        probe: 3
        free: 5
        pay: 9
        mods: 2147483647
        admins: 2147483647
    public:
        x: 0
        default: 0
        probe: 0
        free: 1
        pay: 3
        mods: 2147483647
        admins: 2147483647