VERSION: ${pom.version}
common:
    pageSize: 15
resourceWorld:
    world:
    noWarpsWorlds:
warp:
    minNameLength: 3
    maxNameLength: 25
back:
    limit: 10
# Possible color codes are:
# 0 = Black
# 1 = Dark Blue
# 2 = Dark Green
# 3 = Dark Aqua
# 4 = Dark Red
# 5 = Dark Purple
# 6 = Gold
# 7 = Gray
# 8 = Dark Gray
# 9 = Blue
# a = Green
# b = Aqua
# c = Red
# d = Light Purple
# e = Yellow
# f = White
warpList:
    ownedWarp: 6
    publicWarp: 'b'
    privateWarp: 'c'
warpCounter:
    private:
        x: 0
        default: 0
        probe: 3
        vip: 5
        pay: 9
        mods: 2147483647
        admins: 2147483647
    public:
        x: 0
        default: 0
        probe: 0
        vip: 1
        pay: 3
        mods: 2147483647
        admins: 2147483647