name: FifthElement
main: de.minestar.FifthElement.core.Core
version: ${pom.version}
depend: [MineStarLibrary, MinestarCore]
commands:
  home:
    description: Teleportiert Spieler zum Zuhause
    usage: /home
  setHome:
    description: Erstellt oder versetzt das Zuhause
    usage: /setHome
  homeInfo:
    description: Gibt Informationen ueber das Zuhause aus
    usage: /homeInfo
  bank:
    description: Teleportiert Spieler zu ihrer Bank
    usage: /home
  setBank:
    description: Erstellt oder versetzt die Bank eines Spielers
    usage: /setHome
  bankInfo:
    description: Gibt Informationen ueber die Bank aus
    usage: /homeInfo
  tp:
    description: Teleport den Spieler
    usage: /tp
  tpHere:
    description: Teleportiert die Spieler zum Command caller
    usage: /tpHere
  warp:
    description: Alle Warp Commandos
    usage: /warp