name: FifthElement
main: de.minestar.FifthElement.core.Core
version: ${pom.version}
softdepend: [Illuminati]
depend: [MineStarLibrary, MinestarCore]
commands:
  home:
    description: Teleportiert Spieler zum Zuhause
    usage: /home
  sethome:
    description: Erstellt oder versetzt das Zuhause
    usage: /setHome
  homeinfo:
    description: Gibt Informationen ueber das Zuhause aus
    usage: /homeInfo
  bank:
    description: Teleportiert Spieler zu ihrer Bank
    usage: /home
  setbank:
    description: Erstellt oder versetzt die Bank eines Spielers
    usage: /setHome
  bankinfo:
    description: Gibt Informationen ueber die Bank aus
    usage: /homeInfo
  mine:
    description: Teleportiert Spieler zur Mine
    usage: /mine
  setmine:
    description: Erstellt oder versetzt die Mine
    usage: /setMine
  mineinfo:
    description: Gibt Informationen ueber die Mine aus
    usage: /mineInfo
  tp:
    description: Teleport den Spieler
    usage: /tp
  tphere:
    description: Teleportiert die Spieler zum Command caller
    usage: /tpHere
  warp:
    description: Alle Warp Commandos
    usage: /warp
  back:
    description: Teleportiert den Spieler zum letzten Punkt
    usage: /back